drop extension if exists "pg_net";


  create table "public"."dms" (
    "dm_id" bigint generated by default as identity not null,
    "dm_name" text,
    "dm_icon" text
      );


alter table "public"."dms" enable row level security;


  create table "public"."dms_messages" (
    "message_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message_content" text not null default ''::text,
    "message_image_url" text,
    "user_uuid" bigint,
    "dm_uuid" bigint
      );


alter table "public"."dms_messages" enable row level security;


  create table "public"."dms_users" (
    "user_uuid" uuid not null default auth.uid(),
    "dm_id" bigint not null
      );


alter table "public"."dms_users" enable row level security;


  create table "public"."messages" (
    "message_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message_content" text not null default ''::text,
    "user_uuid" uuid,
    "is_edited" boolean not null default false,
    "message_image_url" text
      );


alter table "public"."messages" enable row level security;


  create table "public"."profiles" (
    "user_id" bigint generated by default as identity not null,
    "profile_image_url" text,
    "username" text not null default ''::text,
    "user_uuid" uuid not null,
    "role" text
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX dms_gc_id_key ON public.dms USING btree (dm_id);

CREATE UNIQUE INDEX dms_messages_message_id_key ON public.dms_messages USING btree (message_id);

CREATE UNIQUE INDEX dms_messages_pkey ON public.dms_messages USING btree (message_id);

CREATE UNIQUE INDEX dms_pkey ON public.dms USING btree (dm_id);

CREATE UNIQUE INDEX messages_message_id_key ON public.messages USING btree (message_id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (message_id);

CREATE UNIQUE INDEX users_id_key ON public.profiles USING btree (user_id);

CREATE UNIQUE INDEX users_name_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX users_pkey ON public.profiles USING btree (user_uuid);

CREATE UNIQUE INDEX users_user_uuid_key ON public.profiles USING btree (user_uuid);

alter table "public"."dms" add constraint "dms_pkey" PRIMARY KEY using index "dms_pkey";

alter table "public"."dms_messages" add constraint "dms_messages_pkey" PRIMARY KEY using index "dms_messages_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."profiles" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."dms" add constraint "dms_gc_icon_check" CHECK ((length(dm_icon) < 200)) not valid;

alter table "public"."dms" validate constraint "dms_gc_icon_check";

alter table "public"."dms" add constraint "dms_gc_id_key" UNIQUE using index "dms_gc_id_key";

alter table "public"."dms" add constraint "dms_gc_name_check" CHECK ((length(dm_name) <= 50)) not valid;

alter table "public"."dms" validate constraint "dms_gc_name_check";

alter table "public"."dms_messages" add constraint "dms_messages_dm_uuid_fkey" FOREIGN KEY (dm_uuid) REFERENCES public.dms(dm_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dms_messages" validate constraint "dms_messages_dm_uuid_fkey";

alter table "public"."dms_messages" add constraint "dms_messages_message_id_key" UNIQUE using index "dms_messages_message_id_key";

alter table "public"."dms_messages" add constraint "dms_messages_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."dms_messages" validate constraint "dms_messages_user_uuid_fkey";

alter table "public"."dms_users" add constraint "dms_users_dm_id_fkey" FOREIGN KEY (dm_id) REFERENCES public.dms(dm_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dms_users" validate constraint "dms_users_dm_id_fkey";

alter table "public"."dms_users" add constraint "dms_users_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES public.profiles(user_uuid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dms_users" validate constraint "dms_users_user_uuid_fkey";

alter table "public"."messages" add constraint "messages_message_content_check" CHECK ((length(message_content) <= 1201)) not valid;

alter table "public"."messages" validate constraint "messages_message_content_check";

alter table "public"."messages" add constraint "messages_message_id_key" UNIQUE using index "messages_message_id_key";

alter table "public"."messages" add constraint "messages_message_image_url_check" CHECK ((length(message_image_url) < 500)) not valid;

alter table "public"."messages" validate constraint "messages_message_image_url_check";

alter table "public"."messages" add constraint "messages_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES public.profiles(user_uuid) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."messages" validate constraint "messages_user_uuid_fkey";

alter table "public"."profiles" add constraint "profiles_profile_image_url_check" CHECK ((length(profile_image_url) < 200)) not valid;

alter table "public"."profiles" validate constraint "profiles_profile_image_url_check";

alter table "public"."profiles" add constraint "profiles_username_check" CHECK ((length(username) < 30)) not valid;

alter table "public"."profiles" validate constraint "profiles_username_check";

alter table "public"."profiles" add constraint "users_id_key" UNIQUE using index "users_id_key";

alter table "public"."profiles" add constraint "users_name_key" UNIQUE using index "users_name_key";

alter table "public"."profiles" add constraint "users_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "users_user_uuid_fkey";

alter table "public"."profiles" add constraint "users_user_uuid_key" UNIQUE using index "users_user_uuid_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  insert into public.profiles (user_uuid, username, profile_image_url)
  values (
    new.id,
    case
      when new.raw_user_meta_data ? 'login' then new.raw_user_meta_data->>'login'
      when new.raw_user_meta_data ? 'preferred_username' then new.raw_user_meta_data->>'preferred_username'
      when new.raw_user_meta_data ? 'user_name' then new.raw_user_meta_data->>'user_name'
      when new.raw_user_meta_data ? 'name' then new.raw_user_meta_data->>'name'
      when  new.raw_user_meta_data ? 'username' then new.raw_user_meta_data->> 'username'
      else 'user_' || left(new.id::text, 8)
    end,
    case
      when new.raw_user_meta_data ? 'avatar_url' then new.raw_user_meta_data->>'avatar_url'
      when new.raw_user_meta_data ? 'picture' then new.raw_user_meta_data->>'picture'
      else 
      new.raw_user_meta_data ->> 'profile_image_url'
    end
  );

  return new;  
end;$function$
;

grant delete on table "public"."dms" to "anon";

grant insert on table "public"."dms" to "anon";

grant references on table "public"."dms" to "anon";

grant select on table "public"."dms" to "anon";

grant trigger on table "public"."dms" to "anon";

grant truncate on table "public"."dms" to "anon";

grant update on table "public"."dms" to "anon";

grant delete on table "public"."dms" to "authenticated";

grant insert on table "public"."dms" to "authenticated";

grant references on table "public"."dms" to "authenticated";

grant select on table "public"."dms" to "authenticated";

grant trigger on table "public"."dms" to "authenticated";

grant truncate on table "public"."dms" to "authenticated";

grant update on table "public"."dms" to "authenticated";

grant delete on table "public"."dms" to "service_role";

grant insert on table "public"."dms" to "service_role";

grant references on table "public"."dms" to "service_role";

grant select on table "public"."dms" to "service_role";

grant trigger on table "public"."dms" to "service_role";

grant truncate on table "public"."dms" to "service_role";

grant update on table "public"."dms" to "service_role";

grant delete on table "public"."dms_messages" to "anon";

grant insert on table "public"."dms_messages" to "anon";

grant references on table "public"."dms_messages" to "anon";

grant select on table "public"."dms_messages" to "anon";

grant trigger on table "public"."dms_messages" to "anon";

grant truncate on table "public"."dms_messages" to "anon";

grant update on table "public"."dms_messages" to "anon";

grant delete on table "public"."dms_messages" to "authenticated";

grant insert on table "public"."dms_messages" to "authenticated";

grant references on table "public"."dms_messages" to "authenticated";

grant select on table "public"."dms_messages" to "authenticated";

grant trigger on table "public"."dms_messages" to "authenticated";

grant truncate on table "public"."dms_messages" to "authenticated";

grant update on table "public"."dms_messages" to "authenticated";

grant delete on table "public"."dms_messages" to "service_role";

grant insert on table "public"."dms_messages" to "service_role";

grant references on table "public"."dms_messages" to "service_role";

grant select on table "public"."dms_messages" to "service_role";

grant trigger on table "public"."dms_messages" to "service_role";

grant truncate on table "public"."dms_messages" to "service_role";

grant update on table "public"."dms_messages" to "service_role";

grant delete on table "public"."dms_users" to "anon";

grant insert on table "public"."dms_users" to "anon";

grant references on table "public"."dms_users" to "anon";

grant select on table "public"."dms_users" to "anon";

grant trigger on table "public"."dms_users" to "anon";

grant truncate on table "public"."dms_users" to "anon";

grant update on table "public"."dms_users" to "anon";

grant delete on table "public"."dms_users" to "authenticated";

grant insert on table "public"."dms_users" to "authenticated";

grant references on table "public"."dms_users" to "authenticated";

grant select on table "public"."dms_users" to "authenticated";

grant trigger on table "public"."dms_users" to "authenticated";

grant truncate on table "public"."dms_users" to "authenticated";

grant update on table "public"."dms_users" to "authenticated";

grant delete on table "public"."dms_users" to "service_role";

grant insert on table "public"."dms_users" to "service_role";

grant references on table "public"."dms_users" to "service_role";

grant select on table "public"."dms_users" to "service_role";

grant trigger on table "public"."dms_users" to "service_role";

grant truncate on table "public"."dms_users" to "service_role";

grant update on table "public"."dms_users" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Enable read access for all users"
  on "public"."messages"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users based on user_uuid"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = user_uuid))
with check ((auth.uid() = user_uuid));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


